sudo: false
language: nix

addons:
  apt:
    packages:
    - gnutls-bin
    - sharutils
    - nodejs
    - gfortran
    - python-minimal
    - python-setuptools
    - python-pip
    - python3-minimal
    - python3-pip
    - python3-setuptools
    - gnupg2
    - dirmngr

cache:
  directories:
  - $HOME/nix.store
  - $HOME/local
  - $HOME/.cask
  - $HOME/node_modules
  - $HOME/.cache/pip
  - $HOME/.evm
  - $HOME/.emacs.d
  - $HOME/Library/Caches/Homebrew
  - $HOME/.pyenv
  - $HOME/Library/Caches/pip

env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$HOME/local/cask/bin:$HOME/local/R/bin:$HOME/local/julia-1.1.0/bin:$PATH

matrix:
  include:
    - os: linux
      env: EMACS_CI=emacs-25-1 IPYTHON=5.8.0 PY=python INSTALL_USER=" --user"
    - os: linux
      env: EMACS_CI=emacs-26-2 IPYTHON=6.5.0 PY=python3 INSTALL_USER=" --user"
    - os: linux
      env: EMACS_CI=emacs-26-3 IPYTHON=7.5.0 PY=python3 INSTALL_USER=" --user"
    - os: osx
      language: generic
      env: EVM_EMACS=emacs-25.2 IPYTHON=5.8.0 PY=python TOXENV=py27 INSTALL_USER=""

  allow_failures:
    - env: EMACS_CI=emacs-snapshot

install:
  - ${PY} -m pip install${INSTALL_USER} --upgrade pip
  - ${PY} -m pip install${INSTALL_USER} wheel
  - sh tools/install-virtualenv.sh
  - |
    if [ "x$TRAVIS_OS_NAME" = "xosx" ]; then
      eval "$(pyenv init -)" ;
      pyenv activate $TOXENV ;
    else
      ${PY} -m pip install${INSTALL_USER} jupyterhub ;
      sudo /usr/bin/npm install -g configurable-http-proxy ;
      ${PY} -m pip install${INSTALL_USER} jupyterhub-dummyauthenticator ;
    fi
  - ${PY} -m pip install${INSTALL_USER} jupyter ipython\<=$IPYTHON jedi\<=0.13.3
  - ${PY} -m pip install${INSTALL_USER} ipykernel
  - ${PY} -m ipykernel install --user
  - ${PY} -m pip install${INSTALL_USER} numpy\<=1.16.0
  - ${PY} -m pip install${INSTALL_USER} matplotlib\<=3.0.2
  - sh tools/install-R.sh
  - sh tools/install-julia.sh
  - |
    if [ "x$TRAVIS_OS_NAME" != "xosx" ]; then
      hash -r
    fi
  - jupyter kernelspec list
  - curl --version
  - ipython --version

before_script:
  - |
    if [ "x$TRAVIS_OS_NAME" = "xosx" ]; then
      sh tools/install-evm.sh
      evm config path $HOME/.evm
      evm install $EVM_EMACS --use --skip
    else
      bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
    fi
  - emacs --version
  - sh tools/install-cask.sh

script:
  - make test-install
  - |
    if [[ "x$TRAVIS_PYTHON_VERSION" == x3* ]]; then
      make test-jupyterhub
    fi
  - rm -rf $HOME/.matplotlib $HOME/.cache/fontconfig
  - make test || ( ( zip -q - log/{testein,testfunc,ecukes}.* 2>/dev/null | uuencode log.zip ) && ( printf "To diagnose, travis logs -i | dos2unix | sed '/^begin 644/,/^end/!d' | uudecode" ) && false)
